[package]
name = "grillon"
version = "0.6.1"
authors = ["theredfish <did.julian@gmail.com>"]
description = "Grillon offers an elegant and natural way to approach API testing in Rust."
repository = "https://github.com/theredfish/grillon"
keywords = ["test", "http", "api", "e2e"]
categories = ["development-tools::testing"]
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["/src", "LICENSE*", "README.md"]
edition = "2021"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
http = "1.4.2"
url = "2.5.8"
futures = "0.3.32"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
jsonpath-rust = "1.0.4"
jsonschema = "0.52.0"
reqwest = { version = "0.13.4", features = ["json", "cookies"] }
thiserror = "2.0.18"
regex = "1.12.4"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["macros"] }
httpmock = "0.8.3"
async-trait = "0.1.89"
test-case = "3.3.1"
surf = "2.3.2"
base64 = "0.22.1"
